[package]
name = "tui-logger"
version = "0.10.0"
authors = ["Jochen Kiemes <jochen@kiemes.de>"]
edition = "2021"
license = "MIT"
description = "Logger with smart widget for the `ratatui` crate"
documentation = "https://docs.rs/tui-logger/latest/tui_logger/"
repository = "https://github.com/gin66/tui-logger"
readme = "README.md"
keywords = ["tui", "log", "logger", "widget", "dispatcher"]

[badges]
travis-ci = { repository = "gin66/tui-logger" }

[dependencies]
log = "0.4"
chrono = { version = "^0.4.20", default-features = false, features = ["clock"] }
tracing = {version = "0.1.37", optional = true}
tracing-subscriber = {version = "0.3", optional = true}
lazy_static = "1.0"
fxhash = "0.2"
parking_lot = "0.12"
ratatui = { version = "0.25.0", default-features = false, package = "ratatui" }
slog = { version = "2.7.0", optional = true }

# Optional features for demo. Unfortunately cannot move to dev-dependencies
termion = {version = "1.5", optional = true }
crossterm = {version = "0.27", optional = true }

[dev-dependencies]
env_logger = "0.10.0"

[features]
default = ["ratatui/termion", "examples-termion"]
slog-support = ["slog"]
tracing-support = ["tracing", "tracing-subscriber"]

# This features are exclusively used by examples/demo.rs
examples-termion = ["termion", "ratatui/termion"]
examples-crossterm = ["crossterm", "ratatui/crossterm"]
